name: Build and scan

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze
    runs-on: [self-hosted]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install the required packages
        run: npm install
          
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Trivy File Scan
        run: trivy fs . --severity HIGH,CRITICAL > fileScanReport.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: techhforvedant21/tictacgame:latest

  Deploy:
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Pull Docker image
        run: docker pull techhforvedant21/tictacgame:latest

      - name: Image scan before deploying to container
        run: trivy image techhforvedant21/tictacgame:latest > imageScanReport.txt

      - name: Deploy Image to container
        run: docker run -d --name game -p 3000:3000 techhforvedant21/tictacgame:latest
      

