name: Build and scan

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze
    runs-on: [self-hosted]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install the required packages
        run: npm install
          
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


